module.exports = [
  {
    item_name: "income",
    amount: 100000,
    date: "01/02/2022",
    from: "Real Estate Investment",
    category: "credit",
  },
  {
    item_name: "income",
    amount: 200000,
    date: "02/27/2022",
    from: "Stock Dividend",
    category: "credit",
  },
  {
    item_name: "income",
    amount: 50000,
    date: "07/21/2022",
    from: "Salary/Jr. Software Engineer",
    category: "credit",
  },
  {
    item_name: "income",
    amount: 30000,
    date: "03/01/2022",
    from: "annual inheritance/Family Estate",
    category: "credit",
  },
  {
    item_name: "groceries",
    amount: 1200,
    date: "07/01/2022",
    from: "grocery list",
    category: "debit",
  },
  {
    item_name: "food-away",
    amount: 2000,
    date: "07/01/2022",
    from: "take-out/dine-in",
    category: "debit",
  },
  {
    item_name: "co-op-maintaince",
    amount: 1000,
    date: "07/01/2022",
    from: "ClevDevs Property Mgt.",
    category: "debit",
  },
  {
    item_name: "internet",
    amount: 100,
    date: "07/01/2022",
    from: "spectrum",
    category: "debit",
  },
  {
    item_name: "utilities",
    amount: 300,
    date: "07/15/2022",
    from: "electric company",
    category: "debit",
  },
  {
    item_name: "car-payment",
    amount: 300,
    date: "07/06/2022",
    from: "Auto finance",
    category: "debit",
  },
  {
    item_name: "car-insurance",
    amount: 350,
    date: "07/21/2022",
    from: "AllState",
    category: "debit",
  },
  {
    item_name: "car-maintance",
    amount: 250,
    date: "07/01/2022",
    from: "car-maintance-saving",
    category: "debit",
  },
  {
    item_name: "gas",
    amount: 200,
    date: "07/01/2022",
    from: "gas station",
    category: "debit",
  },
  {
    item_name: "health-insurance",
    amount: 1000,
    date: "07/01/2022",
    from: "best health insurance",
    category: "debit",
  },
  {
    item_name: "home-owner-insurance",
    amount: 300,
    date: "07/13/2022",
    from: "AllState",
    category: "debit",
  },
  {
    item_name: "savings",
    amount: 30000,
    date: "07/25/2022",
    from: "annual inheritance/Family Estate",
    category: "debit",
  },
  {
    item_name: "family-entertainment",
    amount: 3000,
    date: "07/01/2022",
    from: "movies/outings",
    category: "debit",
  },
  {
    item_name: "vacations",
    amount: 10000,
    date: "08/01/2022",
    from: "Aruba",
    category: "debit",
  },
  {
    item_name: "gifts",
    amount: 5000,
    date: "01/01/2022",
    from: "family/friends",
    category: "debit",
  },

];
